version: '3'
services:
  jupyter-tutorial:
    build: .
    container_name: jupyter.vcloudlab.pro
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./work/:/home/jovyan/work/
    #  - /home/user/.aws/:/home/jovyan/.aws/
    command: start-notebook.sh --NotebookApp.token=''

